In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("medical_data_100.csv")

In [3]:
df

,Patient_ID,Name,Age,Gender,Blood_Group,Diagnosis,Doctor,Visit_Date
0,P001,Neha,40,Female,O-,Migraine,Dr. Reddy,2025-02-06
1,P002,Meena,68,Female,O+,Asthma,Dr. Reddy,2025-05-10
2,P003,Meena,31,Female,B+,Fever,Dr. Sharma,2025-07-08
3,P004,Divya,60,Female,O+,Fever,Dr. Sharma,2025-10-31
4,P005,Priya,67,Male,B+,Asthma,Dr. Mehta,2025-10-22
...,...,...,...,...,...,...,...,...
95,P096,Anita,75,Male,A-,Flu,Dr. Reddy,2025-08-18
96,P097,Kumar,20,Male,AB-,Diabetes,Dr. Mehta,2025-04-09
97,P098,Priya,19,Female,A+,Fever,Dr. Kumar,2025-04-06
98,P099,Ravi,32,Female,O-,Asthma,Dr. Reddy,2025-08-08


In [4]:
data = df.values

In [5]:
data

array([['P001', 'Neha', 40, 'Female', 'O-', 'Migraine', 'Dr. Reddy',
        '2025-02-06'],
       ['P002', 'Meena', 68, 'Female', 'O+', 'Asthma', 'Dr. Reddy',
        '2025-05-10'],
       ['P003', 'Meena', 31, 'Female', 'B+', 'Fever', 'Dr. Sharma',
        '2025-07-08'],
       ['P004', 'Divya', 60, 'Female', 'O+', 'Fever', 'Dr. Sharma',
        '2025-10-31'],
       ['P005', 'Priya', 67, 'Male', 'B+', 'Asthma', 'Dr. Mehta',
        '2025-10-22'],
       ['P006', 'Ravi', 53, 'Male', 'A+', 'Flu', 'Dr. Mehta',
        '2025-08-14'],
       ['P007', 'Priya', 80, 'Female', 'A-', 'Fever', 'Dr. Mehta',
        '2025-07-31'],
       ['P008', 'Neha', 52, 'Female', 'O+', 'Migraine', 'Dr. Mehta',
        '2025-11-09'],
       ['P009', 'Kumar', 47, 'Male', 'B+', 'Hypertension', 'Dr. Mehta',
        '2025-11-17'],
       ['P010', 'Anita', 73, 'Male', 'A-', 'Asthma', 'Dr. Mehta',
        '2025-07-09'],
       ['P011', 'Suresh', 70, 'Male', 'O+', 'Diabetes', 'Dr. Sharma',
        '2025-02-12'],
  

In [7]:
data.ndim

2

In [8]:
data.shape # finding the no.of rows and columns

(100, 8)

In [9]:
data.size # row * columns -> 

800

In [10]:
data.dtype

dtype('O')

In [11]:
data.nbytes

6400

In [13]:
age = df["Age"].to_numpy() # converting to column values to array values

In [14]:
age

array([40, 68, 31, 60, 67, 53, 80, 52, 47, 73, 70, 49, 30, 37, 73, 22, 47,
       56, 56, 29, 51, 66, 64, 66, 71, 74, 61, 77, 55, 28, 60, 50, 26, 77,
       31, 64, 26, 26, 28, 26, 30, 47, 68, 34, 31, 43, 52, 31, 19, 57, 39,
       56, 74, 43, 41, 36, 70, 41, 29, 36, 50, 32, 52, 35, 36, 53, 35, 46,
       69, 79, 67, 64, 58, 69, 56, 70, 61, 41, 59, 33, 27, 32, 20, 56, 54,
       66, 47, 36, 19, 20, 20, 35, 75, 47, 33, 75, 20, 19, 32, 69])

In [15]:
blood_group = df["Blood_Group"].to_numpy()

In [16]:
blood_group

array(['O-', 'O+', 'B+', 'O+', 'B+', 'A+', 'A-', 'O+', 'B+', 'A-', 'O+',
       'A+', 'AB+', 'O-', 'A+', 'B+', 'O+', 'B+', 'B+', 'O+', 'A-', 'O-',
       'O-', 'AB+', 'O+', 'O+', 'B+', 'AB+', 'B-', 'O+', 'O+', 'B+',
       'AB-', 'B-', 'B+', 'B+', 'O+', 'A-', 'AB-', 'O+', 'O+', 'AB+',
       'AB-', 'AB+', 'O+', 'A+', 'A+', 'A+', 'A-', 'A-', 'AB+', 'B+',
       'B-', 'O-', 'O-', 'B+', 'AB+', 'AB+', 'B-', 'AB+', 'AB-', 'B+',
       'O-', 'A+', 'AB+', 'B-', 'AB-', 'O+', 'A-', 'B+', 'AB-', 'A+',
       'B-', 'A-', 'O+', 'A+', 'B-', 'O-', 'AB-', 'O+', 'O-', 'A-', 'AB+',
       'O+', 'B-', 'AB-', 'A+', 'AB-', 'A-', 'A-', 'AB+', 'A-', 'A-',
       'B-', 'AB+', 'A-', 'AB-', 'A+', 'O-', 'A-'], dtype=object)

In [17]:
np.mean("Age")

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U3'), dtype('<U3'), dtype('<U6'))

In [18]:
np.mean(age)

np.float64(48.11)

In [21]:
age[age > 50]

array([68, 60, 67, 53, 80, 52, 73, 70, 73, 56, 56, 51, 66, 64, 66, 71, 74,
       61, 77, 55, 60, 77, 64, 68, 52, 57, 56, 74, 70, 52, 53, 69, 79, 67,
       64, 58, 69, 56, 70, 61, 59, 56, 54, 66, 75, 75, 69])

In [22]:
blood_group[blood_group == 'O+']

array(['O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+',
       'O+', 'O+', 'O+', 'O+', 'O+', 'O+', 'O+'], dtype=object)

In [23]:
diagnosis = df["Diagnosis"].to_numpy()

In [24]:
diagnosis

array(['Migraine', 'Asthma', 'Fever', 'Fever', 'Asthma', 'Flu', 'Fever',
       'Migraine', 'Hypertension', 'Asthma', 'Diabetes', 'Hypertension',
       'Migraine', 'Asthma', 'Diabetes', 'Hypertension', 'Migraine',
       'Hypertension', 'Migraine', 'Asthma', 'Fever', 'Flu', 'Flu',
       'Diabetes', 'Flu', 'Migraine', 'Diabetes', 'Fever', 'Asthma',
       'Hypertension', 'Asthma', 'Diabetes', 'Asthma', 'Asthma',
       'Diabetes', 'Diabetes', 'Fever', 'Fever', 'Fever', 'Fever',
       'Migraine', 'Diabetes', 'Migraine', 'Fever', 'Fever', 'Flu',
       'Migraine', 'Hypertension', 'Asthma', 'Diabetes', 'Hypertension',
       'Fever', 'Migraine', 'Flu', 'Hypertension', 'Asthma', 'Diabetes',
       'Migraine', 'Fever', 'Migraine', 'Flu', 'Fever', 'Migraine', 'Flu',
       'Migraine', 'Asthma', 'Asthma', 'Diabetes', 'Hypertension',
       'Asthma', 'Fever', 'Fever', 'Diabetes', 'Hypertension', 'Migraine',
       'Hypertension', 'Diabetes', 'Diabetes', 'Diabetes', 'Flu', 'Fever',
       'Fe

In [25]:
diagnosis[diagnosis == 'Fever']

array(['Fever', 'Fever', 'Fever', 'Fever', 'Fever', 'Fever', 'Fever',
       'Fever', 'Fever', 'Fever', 'Fever', 'Fever', 'Fever', 'Fever',
       'Fever', 'Fever', 'Fever', 'Fever', 'Fever', 'Fever'], dtype=object)

In [26]:
data[0]

array(['P001', 'Neha', 40, 'Female', 'O-', 'Migraine', 'Dr. Reddy',
       '2025-02-06'], dtype=object)

In [27]:
data[0:5]

array([['P001', 'Neha', 40, 'Female', 'O-', 'Migraine', 'Dr. Reddy',
        '2025-02-06'],
       ['P002', 'Meena', 68, 'Female', 'O+', 'Asthma', 'Dr. Reddy',
        '2025-05-10'],
       ['P003', 'Meena', 31, 'Female', 'B+', 'Fever', 'Dr. Sharma',
        '2025-07-08'],
       ['P004', 'Divya', 60, 'Female', 'O+', 'Fever', 'Dr. Sharma',
        '2025-10-31'],
       ['P005', 'Priya', 67, 'Male', 'B+', 'Asthma', 'Dr. Mehta',
        '2025-10-22']], dtype=object)

In [28]:
data[:,2]

array([40, 68, 31, 60, 67, 53, 80, 52, 47, 73, 70, 49, 30, 37, 73, 22, 47,
       56, 56, 29, 51, 66, 64, 66, 71, 74, 61, 77, 55, 28, 60, 50, 26, 77,
       31, 64, 26, 26, 28, 26, 30, 47, 68, 34, 31, 43, 52, 31, 19, 57, 39,
       56, 74, 43, 41, 36, 70, 41, 29, 36, 50, 32, 52, 35, 36, 53, 35, 46,
       69, 79, 67, 64, 58, 69, 56, 70, 61, 41, 59, 33, 27, 32, 20, 56, 54,
       66, 47, 36, 19, 20, 20, 35, 75, 47, 33, 75, 20, 19, 32, 69],
      dtype=object)

In [29]:
age.mean()

np.float64(48.11)

In [30]:
age.max()

np.int64(80)

In [31]:
age.min()

np.int64(19)

In [33]:
age[(age>50) & (age < 60)]

array([53, 52, 56, 56, 51, 55, 52, 57, 56, 52, 53, 58, 56, 59, 56, 54])

In [34]:
data[0:10]

array([['P001', 'Neha', 40, 'Female', 'O-', 'Migraine', 'Dr. Reddy',
        '2025-02-06'],
       ['P002', 'Meena', 68, 'Female', 'O+', 'Asthma', 'Dr. Reddy',
        '2025-05-10'],
       ['P003', 'Meena', 31, 'Female', 'B+', 'Fever', 'Dr. Sharma',
        '2025-07-08'],
       ['P004', 'Divya', 60, 'Female', 'O+', 'Fever', 'Dr. Sharma',
        '2025-10-31'],
       ['P005', 'Priya', 67, 'Male', 'B+', 'Asthma', 'Dr. Mehta',
        '2025-10-22'],
       ['P006', 'Ravi', 53, 'Male', 'A+', 'Flu', 'Dr. Mehta',
        '2025-08-14'],
       ['P007', 'Priya', 80, 'Female', 'A-', 'Fever', 'Dr. Mehta',
        '2025-07-31'],
       ['P008', 'Neha', 52, 'Female', 'O+', 'Migraine', 'Dr. Mehta',
        '2025-11-09'],
       ['P009', 'Kumar', 47, 'Male', 'B+', 'Hypertension', 'Dr. Mehta',
        '2025-11-17'],
       ['P010', 'Anita', 73, 'Male', 'A-', 'Asthma', 'Dr. Mehta',
        '2025-07-09']], dtype=object)

In [35]:
arr = np.array([1,2,3,4,5])

In [36]:
arr

array([1, 2, 3, 4, 5])

In [38]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [40]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])