# Sale Prediction from Existing Customer - Logistic Regression

## 1. Importing libraries

In [1]:
import pandas as pd
import numpy as np

## 2. importing dataset from dir

In [2]:
dataset = pd.read_csv('DigitalAd_dataset.csv')

In [3]:
dataset

,Age,Salary,Status
0,18,82000,0
1,29,80000,0
2,47,25000,1
3,45,26000,1
4,46,28000,1
...,...,...,...
395,35,65000,0
396,26,80000,0
397,26,52000,0
398,20,86000,0


## 3. Summarize dataset

In [4]:
dataset.head(5)

,Age,Salary,Status
0,18,82000,0
1,29,80000,0
2,47,25000,1
3,45,26000,1
4,46,28000,1


In [5]:
dataset.tail(5)

,Age,Salary,Status
395,35,65000,0
396,26,80000,0
397,26,52000,0
398,20,86000,0
399,32,18000,0


In [6]:
dataset.shape

(400, 3)

In [7]:
dataset.isnull().sum()

Age       0
Salary    0
Status    0
dtype: int64

In [9]:
dataset.dtypes

Age       int64
Salary    int64
Status    int64
dtype: object

##  4.Segerate dataset into X(input) & Y(output)

In [39]:
# before comma rows and after comma columns

# X = dataset.iloc[rowstart:rowend,colstart:colend]
# above form the below data is give. iloc -> means index location
X = dataset.iloc[:, :-1].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [40]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

## 5. Splitting Dataset into Train and Test

In [41]:
from sklearn.model_selection import train_test_split
# 0.25 na testing 25% and training 80% ,, random_state => meaning random 75% data from the dataset
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25,random_state = 0)

### Feature Scaling 
- we scale our data to make all the features contribute equally to the result
- Fit_transform - fit method is calculating the mean and variance of each of the features persent in our data
- Transform - Transform method is transforming all the features using the respective mean and variance
- we want our test data to be a completely new and surprise set of our model

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) # always give fit for training
X_test = sc.transform(X_test)


In [43]:
X_train

array([[ 0.97446763,  0.56400811],
       [-1.52088611, -1.28151705],
       [ 0.30264162,  0.03671521],
       [-0.36918439, -0.81281224],
       [ 0.49459191,  1.20847722],
       [-0.1772341 ,  0.82765456],
       [-0.27320924, -0.78351819],
       [ 0.39861676,  0.24177356],
       [-0.27320924,  0.00742116],
       [ 0.01471619, -0.60775389],
       [ 0.11069133,  0.00742116],
       [-0.46515953,  2.29235707],
       [ 0.39861676, -0.02187289],
       [-0.27320924, -1.28151705],
       [ 1.93421906, -1.39869325],
       [-0.27320924,  2.23376897],
       [ 0.11069133,  1.03271291],
       [-0.56113467,  1.44282962],
       [ 0.97446763,  1.85294632],
       [ 0.30264162,  0.03671521],
       [-1.13698554, -1.04716465],
       [-0.08125895,  0.27106761],
       [ 0.30264162, -0.54916579],
       [-0.27320924, -0.60775389],
       [ 0.87849248, -1.39869325],
       [ 0.78251734, -0.34410744],
       [-0.46515953, -1.252223  ],
       [ 0.20666648,  0.12459736],
       [ 0.39861676,

## 6. Model Training

In [44]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,0
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


### Predicting whether new customer with Age & Salary will buy or not

In [51]:
age = int(input("Enter New Customer Age: "))
sal = int(input("Enter New Customer Salary: "))
newCust = [[age,sal]]
res = model.predict(sc.transform(newCust))
print(res)
if res == 1:
    print("customer will buy!")
else:
    print("customer won't buy!")

Enter New Customer Age:  56
Enter New Customer Salary:  100000


[1]
customer will buy!


## Prediction for all Test data

In [45]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


### Accuracy score

In [46]:
from sklearn.metrics import accuracy_score
print("Accuracy of the Model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Accuracy of the Model: 80.0%


# THE END!